### ISSUE TITLE
 Add Login/Signup Mock, Dark Mode Toggle, and Dynamic Scrolling Trending Section

### ISSUE THREAD

**Issue by Richajaishwal0** [abhrajit2004/Twitter-Landing-Page#12]
Implement a login/signup modal with basic validation, introduce a dark mode toggle using Tailwind CSS, and create a dynamic scrolling section for trending hashtags to enhance interactivity and user experience.

**Comment by abhrajit2004** [comment]
@Richajaishwal0 you can do the rest except the dark mode toggle feature as it's already assigned to other contributor.

**Comment by Richajaishwal0** [comment]
ok thanks
