### ISSUE TITLE
Side menu scrolling with page

### ISSUE THREAD

**Issue by Abhii5496** [abhrajit2004/Twitter-Landing-Page#18]
Hey @abhrajit2004,
![image](https://github.com/user-attachments/assets/38648619-1f9c-4a04-a26c-67da15b12fbf)

Side menu is getting scrolled with page .

Can you please assign this work to me? If possible, kindly add the Hacktoberfest label to the task as well.

**Comment by abhrajit2004** [comment]
@Abhii5496 you are assigned. happy contributing :)
