### ISSUE TITLE
Enhancement: Left Menu 

### ISSUE THREAD

**Issue by nileshkr022** [abhrajit2004/Twitter-Landing-Page#19]
I want to adjust left menu's size to fit in screen and align the menu as in original site. Can you assign this task to me with the hactktoberfest label as well.

**Comment by abhrajit2004** [comment]
@nileshkr022 it was already assigned to issue #18 . You can look for more.

**Comment by nileshkr022** [comment]
> @nileshkr022 it was already assigned to issue #18 . You can look for more.

But he has mentioned about the scrolling only not about alignment.

**Comment by abhrajit2004** [comment]
> > @nileshkr022 it was already assigned to issue #18 . You can look for more.
> 
> But he has mentioned about the scrolling only not about alignment.

you have to align the left menu if you wanna make scrolling feature so both come under same category no??
