### ISSUE TITLE
Change the UI

### ISSUE THREAD

**Issue by abhrajit2004** [abhrajit2004/Twitter-Landing-Page#2]

**Comment by YockerFX** [comment]
So is the goal to upgrade the Design or to make it responsive?

**Comment by abhrajit2004** [comment]
@YockerFX  you can do both

**Comment by abhrajit2004** [comment]
@YockerFX Let us know if you want to work on this issue so I can assign you

**Comment by YockerFX** [comment]
I'm on vacation rn, so I could next week earliest you can leave this issue open for the moment.

**Comment by 5h0ov** [comment]
@YockerFX  hm sure no problem, this is a big work anyways!

**Comment by shubhamkumar9199** [comment]
Hello 
@abhrajit2004 i want to work on this issue.

**Comment by Goutamchoudhary907** [comment]
Hello @abhrajit2004  
I want to work on this plz assign this to me

**Comment by abhrajit2004** [comment]
I have assigned to @Goutamchoudhary907  and @shubhamsharma9199 you guys. Work like a community and wish you guys all the very best. Happy contributing!

( edit: If you guys want to work on different components then just mention this here in the comments before making any edits )

**Comment by abhrajit2004** [comment]
**Add screenshots or video prototypes to your Pull Request to help us understand the effects of the changes that are included in your commits.**

**Comment by Goutamchoudhary907** [comment]
Thanks for assigning this to me @abhrajit2004 
Please clarify what is your goal , suggest something to start

**Comment by 5h0ov** [comment]
> Thanks for assigning this to me @abhrajit2004 Please clarify what is your goal , suggest something to start

@Goutamchoudhary907  like something unique, different and new but pleasing to the eye and responsive. Different than the actual twitter while keep all the functionalities same/similar.

You can focus on individual components if you like, for example the cards(posts) or the profile page, and general color theme or layout of the website.

**Comment by shubhamkumar9199** [comment]
Thanks for assigning us @abhrajit2004 ! Looking forward to collaborating on this. I'll coordinate with @Goutamchoudhary907 to ensure smooth progress. If we decide to work on different components, we'll let you know here before making any edits. Happy to contribute

**Comment by abhrajit2004** [comment]
You guys can also have any kind of conversations with @5h0ov ( collaborator of this repository ) if any problem arises

**Comment by shubhamkumar9199** [comment]
"Thanks for the heads-up @abhrajit2004 ! We'll reach out to @5h0ov  if we run into any issues. Looking forward to working together!"

**Comment by shubhamkumar9199** [comment]
"Could you please elaborate on the problem further? @5h0ov  I’d like to understand your vision more clearly. Specifically, are you looking for unique design elements for individual components, like the posts or profile page, while maintaining the core functionalities similar to Twitter? Additionally, it would be helpful to know if there are any specific themes or layouts you're envisioning. Any examples or inspirations would also be appreciated!

**Comment by abhrajit2004** [comment]
> > Thanks for assigning this to me @abhrajit2004 Please clarify what is your goal , suggest something to start
> 
> @Goutamchoudhary907 like something unique, different and new but pleasing to the eye and responsive. Different than the actual twitter while keep all the functionalities same/similar.
> 
> You can focus on individual components if you like, for example the cards(posts) or the profile page, and general color theme or layout of the website.

@shubhamsharma9199 he has mentioned here. You can follow it

**Comment by Goutamchoudhary907** [comment]
@shubhamsharma9199 bro give your discord or something else

**Comment by 5h0ov** [comment]
> @shubhamsharma9199 bro give your discord or something else

5h0ov

**Comment by Gak1o** [comment]
I want to work on this too

**Comment by shubhamkumar9199** [comment]
@Goutamchoudhary907 My Discord username is shubham007sharma.

**Comment by abhrajit2004** [comment]
> I want to work on this too

@Gak1o bro 2 people are already working on this. So currently more will cause more problems. Once they finish, we will see if UI can be improved more until then create a new issue which you want to work on.

**Comment by abhrajit2004** [comment]
@shubhamsharma9199 @Goutamchoudhary907 If you guys want to make the website responsive, you can also do that. ( This is totally optional )

**Comment by shubhamkumar9199** [comment]
@abhrajit2004 i've made several enhancements to the User Profile Page based on our previous discussions and feedback. Here’s a summary of the changes:

Navbar Color: The upper navigation bar now has a blue background, improving visibility and aesthetics.

Theme Toggle: The theme toggle button changes the background color to blue in both light and dark modes.

Profile Picture Preview: Users can now see a live preview of their profile picture immediately after selecting a new image.

Improved Form Styling: The input fields and buttons have been styled for a more modern look and feel, enhancing the overall user experience.

Success Message: A success message appears when the user updates their profile, providing immediate feedback on the action taken.

**Comment by abhrajit2004** [comment]
@shubhamsharma9199 ok cool! Also make sure to sync your forked repository with the new commits which other contributors did and keep a copy of your work in another folder. Then just push your work in that updated forked repository.
