### ISSUE TITLE
Hamburger Icon Missing on Mobile View

### ISSUE THREAD

**Issue by Ashutosh7-kumar** [abhrajit2004/Twitter-Landing-Page#24]
Please assign this under **"HacktoberFest2024 !"**
Expected Behavior: When the webpage is viewed on a mobile screen (or browser width < 768px), the navigation bar should collapse into a hamburger menu icon, which users can click to open a dropdown navigation menu.

Actual Behavior: The regular navigation bar remains visible without a hamburger icon, and it doesn't adjust to fit the smaller screen properly.

**Comment by abhrajit2004** [comment]
@Ashutosh7-kumar You are assigned now!

**Comment by PRATHAMESH75** [comment]
Please assign it to me.

**Comment by abhrajit2004** [comment]
@Ashutosh7-kumar are you still working on it as I have said to do in your pr?

**Comment by Ashutosh7-kumar** [comment]
@abhrajit2004 I feel sorry but I forgot about this issue and if you want I will fix this by tomorrow morning.

**Comment by abhrajit2004** [comment]
@Ashutosh7-kumar ok 🌸

**Comment by abhrajit2004** [comment]
@PRATHAMESH75 bro this issue has already been assigned to @Ashutosh7-kumar and he has solved it. 
No probs, you can find other issues and raise a new issue yourself.😀
