### ISSUE TITLE
Add Dynamic Animations for Landing Page Interactions

### ISSUE THREAD

**Issue by Niladitya-coder** [abhrajit2004/Twitter-Landing-Page#32]
Enhance the Twitter landing page by adding dynamic animations to improve user interaction and engagement. Key animations include hover effects for buttons/icons, smooth transitions between sections, scroll-based animations for the header and trending section, and interactive feedback for actions like liking or retweeting posts. These animations should be lightweight and optimized for performance across devices.

Please assign the issue for Hacktoberfest and good-first issue.

**Comment by abhrajit2004** [comment]
@Niladitya-coder ok you are assigned

**Comment by Niladitya-coder** [comment]
Thanks!
