### ISSUE TITLE
Add communities button to Sidebar

### ISSUE THREAD

**Issue by dhirajchaurasiya** [abhrajit2004/Twitter-Landing-Page#34]
**Description**
The left Sidebar lacks "Communities" button below the "Grok" button.

![image](https://github.com/user-attachments/assets/f27252cf-bc7f-44c8-85ee-aaa8fc13cc0e)

- Assign me this so that I can contribute to this project.
- Make sure to add ```hacktoberfest``` label to this issue.

Thank you in advance.

**Comment by abhrajit2004** [comment]
@dhirajchaurasiya10 
![image](https://github.com/user-attachments/assets/f018a7a0-4128-44f4-8bf2-453b96c9486d)
bro whatever you have said seems like not so meaningful contribution. You can try to clone the above UI whenever an user clicks on communities button.

**Comment by abhrajit2004** [comment]
@dhirajchaurasiya10 ok you are assigned

**Comment by dhirajchaurasiya** [comment]
@abhrajit2004 did changes. I request you to review cause the deployments didn't satisfy.
