### ISSUE TITLE
Implement Lazy Loading for Media Content to Improve Performance

### ISSUE THREAD

**Issue by Niladitya-coder** [abhrajit2004/Twitter-Landing-Page#37]
The landing page currently loads all images and embedded media (e.g., GIFs, videos) at once, which can negatively impact performance, especially on slower networks. By implementing lazy loading using the loading="lazy" attribute for images and media elements, we can significantly reduce the initial page load time, enhance performance, and improve the user experience across various devices. This will allow media content to load only when it's in the user's viewport, optimizing both bandwidth usage and page responsiveness.
This Issue is for Hacktoberfest2024.

**Comment by abhrajit2004** [comment]
@Niladitya-coder ok go for it

**Comment by Niladitya-coder** [comment]
Thanks
