### ISSUE TITLE
Add a Profile Page

### ISSUE THREAD

**Issue by SouravUpadhyay7** [abhrajit2004/Twitter-Landing-Page#4]
This enhancement introduces a dedicated Profile Page where users can view and update their personal details. The page includes fields for user information such as name, email, bio, and profile picture.

**Comment by abhrajit2004** [comment]
@SouravUpadhyay7 ok you are assigned now. Happy contributing!

**Comment by SouravUpadhyay7** [comment]
Hi @abhrajit2004 ,

Due to some unavoidable circumstances, I won't be able to contribute to the project for the time being. I apologize for any inconvenience. Feel free to assign this task to someone else.

**Comment by ankit071105** [comment]
I can do this please assign this issue to me

**Comment by abhrajit2004** [comment]
@ankit071105 you are assigned now. Happy contributing!
