### ISSUE TITLE
Fixing Bugs

### ISSUE THREAD

**Issue by abhrajit2004** [abhrajit2004/Twitter-Landing-Page#46]
![image](https://github.com/user-attachments/assets/57a9f978-ce95-45d1-b4a4-0fe60570e8e3)
![image](https://github.com/user-attachments/assets/b8a1e8f4-f9e5-489e-acdc-50531a907d46)

Fix these two bugs

**Comment by AmanWebDev2** [comment]
@abhrajit2004 can you assign this to me?

**Comment by abhrajit2004** [comment]
@AmanWebDev2 ok go for it
