### ISSUE TITLE
Feature Request: Add "Scroll to Top" Button

### ISSUE THREAD

**Issue by Saniya1613** [abhrajit2004/Twitter-Landing-Page#49]
I would like to suggest adding a "Scroll to Top" button to improve user navigation, especially for longer pages. This feature would provide a better user experience by allowing users to quickly return to the top of the page without manual scrolling. The button could be implemented using simple HTML and CSS for visibility and smooth scrolling behavior.

This would add functionality and enhance user interaction with the page!

**Comment by abhrajit2004** [comment]
@Saniya1613 ok go for it
