### ISSUE TITLE
Styling issue : I want to improve the look of the landing page sidebar.

### ISSUE THREAD

**Issue by I-Vishal-Kumar** [abhrajit2004/Twitter-Landing-Page#51]
### :: Assign me this issue under Hacktoberfest2024.

<img width="208" alt="{037C55D2-86FB-40E9-9BA7-91B8896C3E30}" src="https://github.com/user-attachments/assets/745afaa6-03b7-4e52-9130-707bc89a79ed">

**Comment by abhrajit2004** [comment]
@I-Vishal-Kumar go for it
