### ISSUE TITLE
dockerizing the project 

### ISSUE THREAD

**Issue by Arnob-B** [abhrajit2004/Twitter-Landing-Page#54]
since it is using npm as package manager , 
dockerizing the whole project will lead to a better management 
and those who dont want to set this project as a developer will be able to view the project just by spinning a container out of the image build

**Comment by abhrajit2004** [comment]
@Arnob-B ok you are assigned

**Comment by Arnob-B** [comment]
hey created a [PR](https://github.com/abhrajit2004/Twitter-Landing-Page/pull/55) for this issue 
plse check it out

**Comment by Arnob-B** [comment]
hey created a [PR](https://github.com/abhrajit2004/Twitter-Landing-Page/pull/57) for this issue
plse check that out
