### ISSUE TITLE
 Add Dark Mode Theme and Basic Animations

### ISSUE THREAD

**Issue by ankit071105** [abhrajit2004/Twitter-Landing-Page#7]
# Description
We need to implement a dark mode theme to improve user experience, especially in low-light environments. Additionally, basic animations will be added to enhance the user interface's responsiveness and interactivity. 
# WANT TO MAKE THE WEBPAGE COMPLETE RESPONSIVE

# Technologies:
CSS: For theme styles and animations (e.g., @keyframes, transform, transition).
JavaScript: For handling the dark mode toggle and persisting user preferences using localStorage.
# Expected Outcome:
A fully functional dark mode theme toggle.
Smooth, subtle animations that enhance user interaction.

**Comment by abhrajit2004** [comment]
> # Description
> We need to implement a dark mode theme to improve user experience, especially in low-light environments. Additionally, basic animations will be added to enhance the user interface's responsiveness and interactivity.
> 
> # WANT TO MAKE THE WEBPAGE COMPLETE RESPONSIVE
> # Technologies:
> CSS: For theme styles and animations (e.g., @Keyframes, transform, transition). JavaScript: For handling the dark mode toggle and persisting user preferences using localStorage.
> 
> # Expected Outcome:
> A fully functional dark mode theme toggle. Smooth, subtle animations that enhance user interaction.

Thanks for coming bro! but this is already assigned to other contributor :(
You can look for more issues :)

**Comment by abhrajit2004** [comment]
@ankit071105 hey do you want to work on profile page? Then I can assign you to do this.

**Comment by ankit071105** [comment]
> @ankit071105 hey do you want to work on profile page? Then I can assign you to do this.

You can but the stored data that user will give to this you have to show that also work both on backend and frontend

**Comment by abhrajit2004** [comment]
@ankit071105 yes. So are you flexible to work on this?

**Comment by abhrajit2004** [comment]
@ankit071105 then you can go the #4 issue and comment there. Then we can assign you

**Comment by 5h0ov** [comment]
> > @ankit071105 hey do you want to work on profile page? Then I can assign you to do this.
> 
> You can but the stored data that user will give to this you have to show that also work both on backend and frontend

yes true a backend is needed but for now you just use dummy data like john doe to design the profile and then if know backend and wanna work on the backend then you can continue with that! It would be a massive contribution! 🌸

**Comment by ankit071105** [comment]
> @ankit071105 yes. So are you flexible to work on this?

yes i can work in front end part complete

**Comment by 5h0ov** [comment]
> > @ankit071105 yes. So are you flexible to work on this?
> 
> yes i can work in front end part complete

can you send a msg in that issue #4 ? Or else cant assign  you

**Comment by ankit071105** [comment]
I have message @5h0ov
