### ISSUE TITLE
Feature: Add hover effect on Post Button.

### ISSUE THREAD

**Issue by shobhit15082003** [abhrajit2004/Twitter-Landing-Page#8]
We can add a **hover effect on Post button** and also we can restyle it to look pleasing.

**Comment by shobhit15082003** [comment]
@5h0ov @abhrajit2004 please assign me this issue and also add hacktoberfest label

**Comment by abhrajit2004** [comment]
@shobhit15082003 ok you are assigned. Happy contributing!

**Comment by 5h0ov** [comment]
> @5h0ov @abhrajit2004 please assign me this issue and also add hacktoberfest label

also while you are at it, don't just add hover effect to Post buttons only! Do the same for the other icons and buttons present, like the Settings icon or Everybody can reply and other similar stuff

**Comment by shobhit15082003** [comment]
@abhrajit2004 @5h0ov I opened a pull request but there seems to be some problem could you please help me resolve them

**Comment by 5h0ov** [comment]
> @abhrajit2004 @5h0ov I opened a pull request but there seems to be some problem could you please help me resolve them

yes we noticed that too but in the end the deploy works

**Comment by shobhit15082003** [comment]
So it is merger able right ?? Please add hacktoberfest label

**Comment by 5h0ov** [comment]
> So it is merger able right ?? Please add hacktoberfest label

look at the pr once i have asked for a review

**Comment by shobhit15082003** [comment]
![Screenshot 2024-10-01 214410](https://github.com/user-attachments/assets/a129f228-cd41-4cba-8c63-7745536ca69f)
![Screenshot 2024-10-01 214417](https://github.com/user-attachments/assets/129a0685-796a-43ae-b17b-97d131609d6b)

This is what I can see ........ Am I supposed to do anything else or everything is done ?

**Comment by 5h0ov** [comment]
@shobhit15082003 
![image](https://github.com/user-attachments/assets/70de77fc-55b8-409e-b70f-b75caa22f29b)

pull the scrollbar down, there is a review comment

**Comment by shobhit15082003** [comment]
https://github.com/user-attachments/assets/f5c810e7-9848-4812-8601-c63bc2a98a71

This is what I see......Is there anything I need to do........(Sorry for asking so many questions.....this is my first time contributing in open source so I am unaware of a lot of things.)

**Comment by 5h0ov** [comment]
> video.mp4 
> This is what I see......Is there anything I need to do........(Sorry for asking so many questions.....this is my first time contributing in open source so I am unaware of a lot of things.)

💀 ok hold on lemme check

**Comment by 5h0ov** [comment]
> video.mp4 
> This is what I see......Is there anything I need to do........(Sorry for asking so many questions.....this is my first time contributing in open source so I am unaware of a lot of things.)

ok i jsut commented in the PR, you can talk there too
