### ISSUE TITLE
Enhancement: Change the verified logo to match the current logo used by twitter to denote verified accounts.

### ISSUE THREAD

**Issue by shobhit15082003** [abhrajit2004/Twitter-Landing-Page#9]
The logo currently used by Twitter is different from the one used here.

**Comment by shobhit15082003** [comment]
@5h0ov @abhrajit2004 please assign me this issue and also add hacktoberfest label.

**Comment by abhrajit2004** [comment]
> The logo currently used by Twitter is different from the one used here.

the twitter logo is also same here bro. You can see the deployed link.

**Comment by shobhit15082003** [comment]
Not the twitter logo but the logo which twitter gives to the verified people below I have attached both the images.
![Screenshot 2024-10-01 210723](https://github.com/user-attachments/assets/f0b27d4c-e84b-4116-9adc-b02662e914d6)
![Screenshot 2024-10-01 210736](https://github.com/user-attachments/assets/f3c92576-eb2f-4e43-ae17-370ecb127997)

**Comment by abhrajit2004** [comment]
> Not the twitter logo but the logo which twitter gives to the verified people below I have attached both the images. ![Screenshot 2024-10-01 210723](https://private-user-images.githubusercontent.com/124374867/372544742-f0b27d4c-e84b-4116-9adc-b02662e914d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTc4MDUsIm5iZiI6MTcyNzc5NzUwNSwicGF0aCI6Ii8xMjQzNzQ4NjcvMzcyNTQ0NzQyLWYwYjI3ZDRjLWU4NGItNDExNi05YWRjLWIwMjY2MmU5MTRkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxNTQ1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmYyYzQxY2ViMzkyZGQ2YWI5MGE4YTQ4YTQ2ZTdjMmE3MmQ3ZTZiZDI5NWE5ZjM3NDk5ZmEwNDI2NGExZjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tMhs1XZGqfwtkgRWZXDPyn1KuXirOu66A5ofDkr7dtY) ![Screenshot 2024-10-01 210736](https://private-user-images.githubusercontent.com/124374867/372544748-f3c92576-eb2f-4e43-ae17-370ecb127997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTc4MDUsIm5iZiI6MTcyNzc5NzUwNSwicGF0aCI6Ii8xMjQzNzQ4NjcvMzcyNTQ0NzQ4LWYzYzkyNTc2LWViMmYtNGU0My1hZTE3LTM3MGVjYjEyNzk5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxNTQ1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTVhOWU1NjUwZWVkNzY0YjJlNjM5OWIzMWNlMGJjYTRhMzcxOTM3YTAwNGRhNTFjZTQwZmMyYmRkNjZkZTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.B_ZKVP79EkbzoaVukSKJt24tN2sPLBASXKme2YEXid4)

Still, it does not come under genuine contribution. You have to add some features or fix any bugs.
